settings.experimental = true

[tools]
rust = { version = "1.95.0", components = "rust-analyzer,clippy,rustfmt" }
lefthook = "2.1.10"
zizmor = "1.27.0"
dprint = "0.55.2"

[hooks]
postinstall = "lefthook install"

[tasks.check]
run = [
  "cargo clippy --fix --allow-dirty --allow-staged",
  "cargo fmt",
  "cargo test --quiet",
  "dprint fmt",
  "zizmor . --offline",
]
